const { PrismaClient } = require("@prisma/client")

const prisma = new PrismaClient()

async function seedDatabase() {
  try {
    const images = [
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1685027982951-taisandradem.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/willrech.jpg?m=1658850348998",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1688912135129-GiacomoTrezza.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/calnunesmendes.png?m=1551921854476",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1714032109135-willames-sales.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/rafael-jenei.jpg?m=1587671315922",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/DWIZARDI.jpg?m=1623445503824",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1702429603951-Vitor-A-Borges.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/leonardopina.jpg?m=1613239203079",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/locutoramarina.jpg?m=1680177832281",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1704545779885-LuanaRenata.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1714501300623-odanineves.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1699106412771-LucasKanes.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1713441445551-diego-luis-da-silva-3.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/AnieMartins.jpg?m=1647365975623",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/Rodrigoecommerce.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1687301542611-Francisco99freelas.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/willrech.jpg?m=1658850348998",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1708126370170-Marcianob.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/caio-gmeiner.jpg?m=1625798025909",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1688029082240-Ana-Ribeiro-BR.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/calnunesmendes.png?m=1551921854476",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1714032109135-willames-sales.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/erickanderson.png?m=1644328770120",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1701128136251-RicharSoares.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1724251930176-emilsonsn.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/jonas-marques.jpg?m=1526617023790",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/wiltonrsp.jpg?m=1595710517809",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1683642867583-djanhsen.design.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/jucamillo.jpg?m=1657566928137",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/EduardaIzeppi.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/paulo.v.avelino.jpg?m=1617471138257",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1726517971207-_gustavodesign_.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1700495749698-ri-guima.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1717172313947-yan-da-silva-rangel.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/LMDesignerComunicacao.png?m=1656961501355",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/SamylaRamos.jpg?m=1619117715834",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1694130317511-mayra.amaral.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1711474641291-GabD.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1704166684054-LizDesign_.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/ABRio.png?m=1679946623609",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1686267097388-GraceMartins.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/alezira.jpg?m=1660252243231",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/ribas-junior.jpg?m=1667934281622",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/luketevl.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/guilherme00pereira.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1721073572977-ana-marcia-dos-santos-gomes.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1719668201652-jheff.designer.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/graciana-lessa.jpg?m=1674244303937",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/Edyoutuber.png?m=1674770215916",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/deyvid.kbh.jpg?m=1",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1714147739637-WavePy.png",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/Wellington_Silva93.png?m=1652741427556",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/anderson-ferreira3.png?m=1665104038237",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/rclgodoi.jpg?m=1597856239039",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1719855046250-fripixel.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/priscca.jpg?m=1628692460488",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1693986178493-alhambra-editora.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/1725481111502-albertogestordemarketing.jpg",
      "https://d2tfco5ldvlr4r.cloudfront.net/profile/210x210/herbert-rischer.jpg?m=1640806634841",
    ]

    const emails = [
      "jessica.silva98@gmail.com",
      "mario.ferreira12@hotmail.com",
      "ana.paula.designer@outlook.com",
      "joao.pedro.dev@gmail.com",
      "camila.arquitetura@hotmail.com",
      "rafael.martins.marketing@outlook.com",
      "beatriz.advogado@gmail.com",
      "carlos.contabilidade@yahoo.com",
      "lucas.sales@outlook.com",
      "mariana.eng.arq@gmail.com",
      "roberto.foto.visual@hotmail.com",
      "juliana.tutor.educacao@outlook.com",
      "pedro.vendas@gmail.com",
      "claudia.suporteadm@hotmail.com",
      "felipe.consultor@gmail.com",
      "aline.ux.ui.design@outlook.com",
      "gabriel.financas@yahoo.com",
      "isabella.escrita@outlook.com",
      "diego.audiovisual@gmail.com",
      "luciana.traducao@hotmail.com",
      "marcelo.marketing.digital@outlook.com",
      "patricia.engenharia@gmail.com",
      "ricardo.web.dev@hotmail.com",
      "simone.contabil@outlook.com",
      "tiago.arquiteto@gmail.com",
      "vanessa.educacao.consultoria@hotmail.com",
      "marcos.juridico@outlook.com",
      "daniela.suporteadm@gmail.com",
      "guilherme.desenvolvedor.web@hotmail.com",
      "carolina.atendimento@outlook.com",
      "daniel.vendas.marketing@gmail.com",
      "luiz.eng.arq@hotmail.com",
      "renata.fotografia@outlook.com",
      "anderson.financas@gmail.com",
      "fernanda.tutor.educacao@hotmail.com",
      "victor.advogado@outlook.com",
      "helena.marketing.digital@gmail.com",
      "rodrigo.dev.web@hotmail.com",
      "aline.suporteadm@outlook.com",
      "vinicius.consultoria@gmail.com",
      "lara.design.creation@hotmail.com",
      "bruno.contabilidade@outlook.com",
      "sabrina.juridico@gmail.com",
      "fabio.audiovisual@hotmail.com",
      "eduardo.arquiteto@outlook.com",
      "leticia.tradutor@gmail.com",
      "cintia.vendas.marketing@hotmail.com",
      "paulo.engenheiro@outlook.com",
      "rafaela.web.mobile@gmail.com",
      "roberto.design.creation@hotmail.com",
      "monica.suporteadm@outlook.com",
      "igor.consultor@gmail.com",
      "camila.dev.web@hotmail.com",
      "flavia.marketing.digital@outlook.com",
      "hugo.eng.arq@gmail.com",
      "marcela.contabilidade@hotmail.com",
      "jose.advocacia@outlook.com",
      "ana.fotografia@gmail.com",
      "mirella.bio@outlook.com",
      "alex.dev@gmail.com",
    ]

    const creativeNames = [
      "Lucas Andrade",
      "Amanda Fernandes",
      "Bruno Silva",
      "Camila Oliveira",
      "Felipe Souza",
      "Mariana Costa",
      "Gabriel Pereira",
      "Isabela Carvalho",
      "João Vitor Martins",
      "Rafaela Lima",
      "Pedro Almeida",
      "Julia Ribeiro",
      "Thiago Melo",
      "Luana Freitas",
      "Daniel Castro",
      "Ana Clara Rocha",
      "Rafael Santos",
      "Beatriz Gomes",
      "Leonardo Barbosa",
      "Carolina Nogueira",
      "Diego Araújo",
      "Letícia Correia",
      "Gustavo Monteiro",
      "Fernanda Mendes",
      "Victor Guimarães",
      "Larissa Duarte",
      "Rodrigo Farias",
      "Bruna Pires",
      "Vinícius Teixeira",
      "Patrícia Campos",
      "Henrique Assis",
      "Natália Ramos",
      "Marcelo Batista",
      "Vanessa Martins",
      "Eduardo Ferreira",
      "Clarice Moreira",
      "André Cardoso",
      "Lorena Borges",
      "Renato Bezerra",
      "Giovana Almeida",
      "Fábio Rezende",
      "Sabrina Vieira",
      "Igor Barros",
      "Tatiane Silveira",
      "Cláudio Moura",
      "Helena Matos",
      "Ricardo Cunha",
      "Sofia Azevedo",
      "Alexandre Lopes",
      "Débora Pinheiro",
      "Maurício Tavares",
      "Verônica Brito",
      "Rômulo Vieira",
      "Juliana Machado",
      "Cristiano Albuquerque",
      "Priscila Cruz",
      "Otávio Henrique",
      "Melissa Silva",
      "Douglas Nascimento",
      "Fabiana Lopes",
    ]

    const addresses = [
      "São Paulo",
      "Rio de Janeiro",
      "Belo Horizonte",
      "Salvador",
      "Curitiba",
      "Porto Alegre",
      "Fortaleza",
      "Brasília",
      "Recife",
      "Manaus",
      "Goiânia",
      "Belém",
      "Florianópolis",
      "Campinas",
      "Maceió",
      "Natal",
      "São Luís",
      "Teresina",
      "João Pessoa",
      "Aracaju",
      "Cuiabá",
      "Campo Grande",
      "Vitória",
      "Macapá",
      "Boa Vista",
      "Palmas",
      "Santos",
      "Ribeirão Preto",
      "Sorocaba",
      "Uberlândia",
      "Juiz de Fora",
      "Blumenau",
      "Maringá",
      "Londrina",
      "Caxias do Sul",
      "São José dos Campos",
      "Niterói",
      "Petrolina",
      "Vila Velha",
      "Caruaru",
      "Canoas",
      "Foz do Iguaçu",
      "Itajaí",
      "Joinville",
      "Anápolis",
      "Pelotas",
      "Piracicaba",
      "Bauru",
      "Cascavel",
      "Chapecó",
      "Jundiaí",
      "Marabá",
      "Aparecida de Goiânia",
      "Passo Fundo",
      "Santarém",
      "Montes Claros",
      "Dourados",
      "Volta Redonda",
      "Vitória da Conquista",
      "Araguaína",
      "Rondonópolis",
      "Ilhéus",
    ]

    const descriptions = [
      // Administração e Contabilidade
      "Consultor financeiro especializado em análise de fluxo de caixa e planejamento tributário.",
      "Gestor administrativo com experiência em otimização de processos empresariais e controle de custos.",
      "Analista contábil com foco em contabilidade fiscal, balanço patrimonial e relatórios financeiros.",
      "Especialista em folha de pagamento e compliance trabalhista para pequenas e médias empresas.",
      "Consultor de negócios com experiência em reestruturação empresarial e gestão de equipes.",

      // Advogados & Leis
      "Advogado especializado em direito civil, com experiência em contratos e mediação de conflitos.",
      "Consultor jurídico para empresas, com foco em direito societário e contratos comerciais.",
      "Especialista em direito trabalhista, atuando em causas de vínculo empregatício e negociações sindicais.",
      "Advogado tributarista com experiência em planejamento fiscal e recuperação de tributos.",
      "Consultor legal com foco em compliance empresarial e governança corporativa.",

      // Atendimento ao Consumidor
      "Especialista em atendimento ao cliente, focado em soluções rápidas e eficientes via chat e e-mail.",
      "Consultor de suporte ao cliente com experiência em gestão de CRM e resolução de conflitos.",
      "Profissional de atendimento com foco em satisfação do cliente e otimização de processos de suporte.",
      "Especialista em pós-venda, garantindo a fidelização e retenção de clientes.",
      "Consultor de atendimento ao cliente com experiência em call centers e suporte remoto.",

      // Design & Criação
      "Designer gráfico especializado em criação de logotipos e identidade visual para empresas.",
      "Ilustrador digital com foco em desenvolvimento de personagens e animações 2D.",
      "Designer UX/UI com experiência em prototipagem de interfaces para aplicativos móveis e web.",
      "Designer de embalagens com foco em soluções criativas e sustentáveis para produtos de consumo.",
      "Artista gráfico com expertise em criação de material promocional e campanhas publicitárias.",

      // Educação & Consultoria
      "Consultor educacional especializado em desenvolvimento de estratégias de ensino online.",
      "Professor de inglês com experiência em ensino de idiomas para negócios e viagens.",
      "Consultor de treinamento corporativo com foco em liderança e desenvolvimento de equipes.",
      "Tutor de matemática, oferecendo aulas particulares para estudantes do ensino médio e universitário.",
      "Consultor de metodologias ágeis, ajudando empresas a implementar Scrum e Kanban.",

      // Engenharia & Arquitetura
      "Engenheiro civil com experiência em construção e gerenciamento de projetos residenciais.",
      "Arquiteto especializado em design de interiores e otimização de espaços.",
      "Engenheiro elétrico com experiência em projetos de instalações prediais e industriais.",
      "Consultor de engenharia estrutural, com foco em análise de segurança e viabilidade.",
      "Arquiteto paisagista com experiência em planejamento de áreas verdes e projetos sustentáveis.",

      // Escrita
      "Redator publicitário com experiência em criação de textos persuasivos para campanhas de marketing.",
      "Escritor freelance com foco em produção de artigos para blogs e sites institucionais.",
      "Copywriter especializado em e-mail marketing e páginas de vendas.",
      "Revisor de textos com experiência em correção de artigos acadêmicos e publicações editoriais.",
      "Criador de conteúdo com expertise em roteiros para vídeos e podcasts.",

      // Fotografia & AudioVisual
      "Fotógrafo profissional especializado em ensaios fotográficos e eventos corporativos.",
      "Videomaker com experiência em edição de vídeos e criação de conteúdo audiovisual para redes sociais.",
      "Editor de áudio com foco em mixagem e masterização de trilhas sonoras e podcasts.",
      "Fotógrafo de produtos, ajudando empresas a destacar seus itens em lojas online.",
      "Videomaker especializado em produção de vídeos institucionais e campanhas publicitárias.",

      // Suporte Administrativo
      "Assistente virtual com experiência em gestão de e-mails, organização de agendas e suporte remoto.",
      "Consultor administrativo focado em otimização de processos e fluxo de trabalho.",
      "Secretário executivo com expertise em organização de reuniões e gerenciamento de documentos.",
      "Profissional de suporte administrativo com foco em controle de inventário e gestão de fornecedores.",
      "Especialista em organização de eventos corporativos e gestão de logística.",

      // Tradução
      "Tradutor de inglês para português com foco em documentos técnicos e acadêmicos.",
      "Tradutor especializado em tradução jurídica, com experiência em contratos e documentos legais.",
      "Intérprete de conferências, especializado em eventos empresariais e reuniões internacionais.",
      "Tradutor audiovisual com foco em legendagem e dublagem de filmes e séries.",
      "Especialista em tradução de marketing, adaptando campanhas publicitárias para mercados internacionais.",

      // Vendas & Marketing
      "Consultor de marketing digital especializado em SEO e campanhas de Google Ads.",
      "Gestor de tráfego pago com experiência em Facebook Ads e estratégias de remarketing.",
      "Consultor de vendas B2B, especializado em prospecção de novos clientes e fechamento de negócios.",
      "Especialista em e-commerce com foco em plataformas como Shopify e WooCommerce.",
      "Consultor de branding, ajudando empresas a desenvolver estratégias de marca e posicionamento no mercado.",

      // Web, Mobile & Software
      "Desenvolvedor full-stack com experiência em JavaScript, React e Node.js.",
      "Especialista em desenvolvimento mobile, com foco em aplicativos iOS e Android.",
      "Desenvolvedor backend especializado em criação de APIs RESTful e bancos de dados relacionais.",
      "Engenheiro de software com experiência em arquitetura de sistemas e microservices.",
      "Programador front-end com expertise em HTML, CSS, JavaScript e frameworks como Vue.js.",
    ]

    // Criar 60 profissionais com nomes e endereços fictícios
    const specialists = []
    for (let i = 0; i < 60; i++) {
      const name = creativeNames[i]
      const address = addresses[i]
      const imageUrl = images[i]
      const description = descriptions[i]
      const email = emails[i]

      const specialist = await prisma.user.create({
        data: {
          name,
          email,
          password: process.env.PASSWORD_USERS_FAKE,
          accountType: "specialist",
          image: imageUrl,
          about: description,
          city: address,
        },
      })

      await prisma.contact.create({
        data: {
          type: "Whatsapp/Telefone",
          contact: "(16) 99999-9999",
          user: { connect: { id: specialist.id } },
        },
      })

      specialists.push(specialist)
    }

    // Fechar a conexão com o banco de dados
    await prisma.$disconnect()
  } catch (error) {
    console.error("Erro ao criar as barbearias:", error)
  }
}

seedDatabase()
